### ISSUE TITLE
Cocoapods integration

### ISSUE THREAD

**Issue by WedgeSparda** [Darkseal/DownPicker#10]
Will be possible to install this picker using cocoapods in the future?

Thanks.

**Comment by Darkseal** [comment]
Hello,

Yes it's basically all already setup: I just need to add the .podspec and LICENSE files, I'll do that in the next 1-2 days. Stay tuned!

**Comment by nonannoyance** [comment]
+1

**Comment by Darkseal** [comment]
I've just finished the CocoaPods integration and updated the README.md accordingly. Please let me know if everything is working as it should.

**Comment by WedgeSparda** [comment]
It worked :) 

Thanks
