### ISSUE TITLE
Add "set default option" feature

### ISSUE THREAD

**Issue by WedgeSparda** [Darkseal/DownPicker#14]
It would be great to add a property to set a default selected option from the dataArray. This way, picker would show a selected option since the beginning.

**Comment by Darkseal** [comment]
What about adding a setter to the `text` property? We can handle it just like the text contained in the textField, as it would mostly be a shortcut for that (as it already is now): we also already have all the checks in place (see #11 and #12) to handle wrong input data.

**Comment by WedgeSparda** [comment]
The idea would be something like this:
[picker setSelectedOptionIndex:3];

Then, the text field text would match that option's string value.

This way, you could change picker's value programmatically too.

**Comment by Darkseal** [comment]
Aah ok: you want to set a default selected option _index_ too. I'll do both things this evening.

**Comment by WedgeSparda** [comment]
Yes, the important thing here is to avoid that the default selected text doesn't exists in the data array.

**Comment by Darkseal** [comment]
Actually the option was already there, `setDefaultValue` was doing exactly that. Anyway, I added a setter for `text` and a `selectedIndex` property with getter and setter, both of them supporting empty (nil) values, so you can programmatically reset the DownPicker initial state ("clearing" the user selection) by setting `text = nil` or `selectedIndex = nil`.

I also setup some basic unit testing, now the CI build is passing aswell ^_^

Please let me know if everything is working as intended.
