### ISSUE TITLE
Text inside text field is selectable

### ISSUE THREAD

**Issue by WedgeSparda** [Darkseal/DownPicker#22]
It would be great to avoid text selection inside a text field used as a DownPicker.

**Comment by Darkseal** [comment]
Task here was to avoid subclassing and also preserve the "ontouch" capability of the `UITextField`. I think i found a way to ensure both: check 0.1.30 and let me know if it works like you want.

**Comment by WedgeSparda** [comment]
Um, just updated and textfield keeps letting me select the text inside.

**Comment by Darkseal** [comment]
Ok, I'll revert the code back then since it doesn't work and also creates issues (see #23)
