### ISSUE TITLE
Multiple Down Pickers 

### ISSUE THREAD

**Issue by ValentinDenis** [Darkseal/DownPicker#25]
When I set up multiple down pickers in the same pages, If I choose an option for one, it disables all the others.
EDIT: Same if I have another classic UITextField and I type in a value.

**Comment by Darkseal** [comment]
Added an Example project to the repository who shows how to implement multiple downpickers in a single View. Let me know if it solves your issue.

**Comment by johnrajahkkd** [comment]
I solved it like below.

in .h file 
@property (nonatomic) DownPicker *picker1;
@property (nonatomic) DownPicker *picker2;

in .m file 
NSArray *array1 = @[@"data 1", @"data 2", @"data 3"];
self.picker1 = [[DownPicker alloc] initWithTextField:self.priceTierTF withData:array1];
    
NSArray *array2 = @[@"data 1", @"data 2", @"data 3"];
self.picker2 = [[DownPicker alloc] initWithTextField:self.priceTierTF withData:array2];
