### ISSUE TITLE
Dropdown Icon Pixelated on iPhone 6

### ISSUE THREAD

**Issue by jamesvandyne** [Darkseal/DownPicker#3]
The dropdown icon is only available in standard resolution, which makes it look pixelated on iPhone 6.
We should include the following icons:
downArrow.png  (32x24)  [Already exists]
downArrow@2x.png (64x48)
downArrow@3x.png (96x72)

![screen shot 2015-05-19 at 14 51 22](https://cloud.githubusercontent.com/assets/154726/7712353/94412774-fe36-11e4-9c96-3c45937f17b6.png)

I'd be glad to make and test these if you have a large source image I can start with. 

Thanks!

James

**Comment by Darkseal** [comment]
I tried to make it: please let me know if they're satisfying enough :)

**Comment by jamesvandyne** [comment]
They work and look great!
Thanks!
James
