### ISSUE TITLE
Add Clear button 

### ISSUE THREAD

**Issue by chlebta** [Darkseal/DownPicker#8]
Hello, How to add clear button to diselect the row ?

**Comment by Darkseal** [comment]
Hello,
currently the "clear" functionality isn't supported. I'll look into it and see what I can do.

**Comment by Darkseal** [comment]
I added a basic "clearing" functionality, you can clear the user selection by setting the `text` property to `nil`. That way you can add a button anywhere to do it programmatically and reset/clear the DownPicker.
