### ISSUE TITLE
UIDownPicker how to use?

### ISSUE THREAD

**Issue by furueili** [Darkseal/DownPicker#9]
hi ~I am confused that  UIDownPicker example code how to use?
please give me more detail to use,thx

**Comment by Darkseal** [comment]
You instantiate it, configure it and then add it into a container control (or into the containing view) using the container's `addSubview` method. Each step is shown in my sample code. For further examples, read my post here:

http://www.ryadel.com/2015/03/31/downpicker-drop-down-list-combobox-for-ios-in-objective-c/

If you need further samples, read this StackOverflow question and the accepted answer (they talk about an UIButton but the UIDownPicker works just like that):

http://stackoverflow.com/questions/1378765/how-do-i-create-a-basic-uibutton-programmatically

Happy coding!
